sudo: required
os: linux
language: node_js
services:
  - docker
before_install:
  - docker build -t amirftma/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true amirftma/docker-react npm run test